name = 'torchutils'
path = 'torchutils'
version = '0.1.0'
author = 'Scott Lowe'
author_email = 'scott.code.lowe@gmail.com'
description = 'Utility functions for pytorch'
url = 'https://github.com/scottclowe/pytorch'
license = 'MIT'
